LNG-RK:
  H0S0ReferenceState:
    T_ref: 25 degC
    dh_form:  # heat of formation
      C3: -104.7 kJ/mol
      nC4: -125.6 kJ/mol
    p_ref: 1.0 bar
    s_0:
      C3: 0.0 J/(mol*K)  # missing
      nC4: 0.0 J/(mol*K)  # missing
  LinearHeatCapacity:
    cp_a:
      C3: 0.0 J/(mol*K)  # missing
      nC4: 0.0 J/(mol*K)  # missing
    cp_b:
      C3: 0.0 J/(mol*K**2)  # missing
      nC4: 0.0 J/(mol*K**2)  # missing
  CriticalParameters:
    T_c:
      C3: 369.8 K
      nC4: 425.2 K
    omega:
      C3: 0.153 dimless
      nC4: 0.199 dimless
    p_c:
      C3: 42.5 bar
      nC4: 38.0 bar
  BostonMathiasAlphaFunction:
    eta:
      C3: 0 dimless
      nC4: 0 dimless
  MixingRule_A:
    T_ref: 25 degC
  MixingRule_C:
    c_i:
      C3: 0.0 m**3/mol  # missing
      nC4: 0.0 m**3/mol # missing

Water-RK:
  H0S0ReferenceState:
    T_ref: 25 degC
    dh_form:
      H2O: -241.826 kJ/mol
    p_ref: 1.0 bar
    s_0:
      H2O: 0.0 J/(mol*K)  # missing
  LinearHeatCapacity:
    cp_a:
      H2O: 0.0 J/(mol*K)  # missing
    cp_b:
      H2O: 0.0 J/(mol*K**2)
  CriticalParameters:
    T_c:
      H2O: 647 K
    omega:
      H2O: 0.344 dimless
    p_c:
      H2O: 220.64 bar
  BostonMathiasAlphaFunction:
    eta:
      H2O: 0 dimless
  MixingRule_A:
    T_ref: 25.0 degC
  MixingRule_C:
    c_i:
      H2O: 0.0 m**3/mol  # missing
