[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SigmaMu"
description = "Equation oriented process modelling library"
version = "1.0b2"  # THIS IS THE MASTER TAG FOR THE VERSION
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Volker Siepmann", email = "volker.siepmann@gmail.com" }
]
license = { text = "LGPL-3.0-or-later" }
requires-python = ">=3.12"
keywords = ["thermodynamics", "modelling"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Chemistry",
]

dependencies = [
    "pint",
    "numpy",
    "scipy",
    "pypardiso",
    "casadi",
    "pyyaml",
    "pydantic"
]

[project.urls]
Homepage = "https://github.com/VolkerSiep/SigmaMu"
Documentation = "https://sigmamu.readthedocs.io/en/latest/"
Repository = "https://github.com/VolkerSiep/SigmaMu.git"
Issues = "https://github.com/VolkerSiep/SigmaMu/issues"
Changelog = "https://sigmamu.readthedocs.io/en/latest/release_notes.html"

[project.optional-dependencies]
doc = [
    "Sphinx",
    "sphinxcontrib-bibtex",
    "sphinx-copybutton",
]

dist = [
    "build",
    "twine",
    "setuptools",
    "wheel"
]

test = [
    "pytest",
    "pytest-doctestplus",
    "pytest-cov"
]

dev = [
    "matplotlib",
    "scipy-stubs",
    "pytest",
    "pytest-doctestplus",
    "pytest-cov",
    "build",
    "twine",
    "Sphinx",
    "sphinxcontrib-bibtex",
    "sphinx-copybutton",
    "setuptools",
    "wheel"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
simu = ["py.typed"]
"*" = [
    "src/simu/**/*.yml",
    "src/simu/core/data/uom_definitions.txt",
]

[tool.pytest.ini_options]
doctest_plus = "enabled"
addopts = "--doctest-rst -q --tb=short -s --cov --cov-report=html"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
testpaths = [
    "doc/source",
    "src/simu",
    "unittests"
]
norecursedirs =  [
    "src/simu/examples"
]

[tool.coverage.run]
branch = true
omit = [
    "src/simu/examples/**",
    "**/__init__.py"
]

[tool.coverage.report]
skip_covered = true

