H0S0ReferenceState:
  T_ref: 298.15
  dh_form:
    C3: -104700.0
    nC4: -125600.0
  p_ref: 100000.0
  s_0:
    C3: 0.0  # missing
    nC4: 0.0  # missing
LinearHeatCapacity:
  cp_a:
    C3: 0.0  # missing
    nC4: 0.0  # missing
  cp_b:
    C3: 0.0  # missing
    nC4: 0.0  # missing
CriticalParameters:
  T_c:
    C3: 369.8
    nC4: 425.2
  omega:
    C3: 0.153
    nC4: 0.199
  p_c:
    C3: 4250000.0
    nC4: 3800000.0
BostonMathiasAlphaFunction:
  eta:
    C3: 0
    nC4: 0
MixingRule_A:
  T_ref: 298.15
MixingRule_C:
  c_i:
    C3: 0.0  # missing
    nC4: 0.0  # missing
