species: {H2O: H2O}

phases:
  liquid: {frame: liquid, species: [H2O]}
  gas: {frame: gas, species: [H2O]}

frames:
  liquid:
    state: GibbsState
    contributions:
      - {name: H0S0_Liquid, cls: H0S0ReferenceState}
      - {name: Cp_Liquid, cls: BarinHeatCapacity}
      - MolecularWeight
      - IdealMix
      - cls: PolynomialGibbsVolume
        options:
          order: 2
      - GenericProperties
  gas:
    state: HelmholtzState
    contributions:
      - {name: H0S0_Gas, cls: H0S0ReferenceState}
      - {name: Cp_Gas, cls: BarinHeatCapacity}
      - MolecularWeight
      - HelmholtzIdealGas
      - CriticalParameters
      - BostonMatthiasMFactor
      - BostonMathiasAlphaFunction
      - RedlichKwongAFunction
      - RedlichKwongBFunction
      - cls: NonSymmetricMixingRule
        name: MixingRule_A
        options:
          target: _ceos_a
      - cls: LinearMixingRule
        name: MixingRule_B
        options:
          target: _ceos_b
      - RedlichKwongEOSGas
      - GenericProperties

parameters:
  IAPWS_fit:
    Cp_Gas:
      A: {H2O: 3.36040652e+01  J/K/mol}
      B: {H2O: 9.87726427e-03 J/K/mol}
      C: {H2O: 4.07601537e-06 J/K/mol}
      D: {H2O: 0 J/K/mol}
      E: {H2O: 7.44650670e+02 J/K/mol}
      F: {H2O: 0 J/K/mol}
      G: {H2O: 0 J/K/mol}
      T_scale: 1 K
    Cp_Liquid:
      A: {H2O: 7.53183864e+01 J/K/mol}
      B: {H2O: 8.04871326 J/K/mol}
      C: {H2O: -1.58775628e-02 J/K/mol}
      D: {H2O: 1.18052352e-05 J/K/mol}
      E: {H2O: 1.54473206e+05 J/K/mol}
      F: {H2O: 0 J/K/mol}
      G: {H2O: 0 J/K/mol}
      T_scale: 1 K
    H0S0_Gas:
      T_ref: 25 degC
      p_ref: 1 bar
      dh_form: {H2O: -241.826 kJ/mol}
      s_0: {H2O: 188.835 J/K/mol}
    H0S0_Liquid:
      T_ref: 25 degC
      p_ref: 1 bar
      dh_form: {H2O: -285.830 kJ/mol}
      s_0: {H2O: 69.95 J/K/mol}
    PolynomialGibbsVolume:
      T_ref: 25 degC
      A: {H2O: 18 cm^3/mol}
      B: {H2O: 0 cm^3/mol}
      C: {H2O: 0 cm^3/mol}
    BostonMathiasAlphaFunction:
      eta:
        H2O: 0.0
    CriticalParameters:
      T_c:
        H2O: 647.096 K
      omega:
        H2O: 0.344
      p_c:
        H2O: 220.60 bar
    MixingRule_A:
      T_ref: 25 degC